### ISSUE TITLE
Can't update, zip file does not exist

### ISSUE THREAD

**Issue by notrealdan** [MeusRex/pf2e-chex#14]
The module.json file points to this file that doesn't exist:
https://github.com/MeusRex/pf2e-chex/archive/refs/tags/chex-v1.1.0.zip

So, the following error appears in Foundry when checking for module updates:
![image](https://github.com/MeusRex/pf2e-chex/assets/28198633/6b10f821-2e09-40c9-a0d0-3dabc16e6f98)

**Comment by Ackerfe** [comment]
It's mentioned here: [https://github.com/MeusRex/pf2e-chex/discussions/13](url) 
For now you need to update manually, altough I don't think I've seen a new update in the releases since 1.0.2

**Comment by MeusRex** [comment]
I messed up, I increased version to v1.1.0 in the manifest but named the release something else.
Should be fixed now.

**Comment by notrealdan** [comment]
So, now I don't get an error, but every time I have Foundry check for updates, it "updates" this module from version 1.0.2 to 1.0.2.  This is because module.json now has:
"download": "https://github.com/MeusRex/pf2e-chex/archive/refs/tags/chex-v1.0.2.zip",

but it also has this version declared:
"version": "1.1.0",
 
That makes Foundry think that 1.1.0 is available, but downloads and installs the 1.0.2 zip file.  If the 1.1.0 zip file is available now (it seems to be), I suggest updating the module.json to point to it.  Otherwise, change the version entry back to 1.0.2 so Foundry doesn't continue to have an update loop.

**Comment by MeusRex** [comment]
It's really annoying that foundry violates one of the cardinal rules. Commited code shouldn't have any inpacts on previous releases...

I've fixed the manifest, missed the version field. I've also deleted the 1.1.0 release. I realised that it contains some unfinished work. E.g. fog of war support works for the overlay, but the HUD still shows everything, even in unexplored places. Now everything should point to 1.0.2 once again. I guess I'll just have to remember to update the manifest when I do a release and not in preparation of a release. Sigh.

**Comment by notrealdan** [comment]
Thanks for fixing it.

One way I've seen module authors handle it is to have the module.json and the module zip file as part of each release and link to the "latest" release.  That way, Foundry isn't linking to the copy you're actively developing on, but instead pointing at something like (I just these links, they don't go anywhere right now):
`https://github.com/MeusRex/pf2e-chex/releases/latest/download/module.json`

which points to something like this for the download:
`https://github.com/MeusRex/pf2e-chex/releases/latest/download/module.zip`

At each release, that link could stay the same as it'll always point users to the newest version you're released, and not a working copy.
