### ISSUE TITLE
v12 Compatibility?

### ISSUE THREAD

**Issue by jsouthwick4494** [MeusRex/pf2e-chex#22]
Not sure if this mod is still under development, but figured I'd post to see if v12 compatibility is possible.

**Comment by MeusRex** [comment]
Not at the moment. I'm busy with other projects and running sessions. I haven't even looked into any changes I would have to make to get it running. So, it will stay like this until I feel the need to update my own foundry.
Maybe I'll take a look at some point to check how much effort it would be, but I can't make any promises.

**Comment by MeusRex** [comment]
Thank's to gralamin, this issue is now resolved
