### ISSUE TITLE
Foundry V12 Compatiblity

### ISSUE THREAD

**Issue by miki4920** [MeusRex/pf2e-chex#23]
Hi,

Was just wondering if there are any plans on updating this module to Foundry 12?

Thanks

**Comment by MeusRex** [comment]
Not at the moment. I'm busy with other projects and running sessions. I haven't even looked into any changes I would have to make to get it running. So, it will stay like this until I feel the need to update my own foundry.
Maybe I'll take a look at some point to check how much effort it would be, but I can't make any promises.

**Comment by MeusRex** [comment]
Thank's to gralamin this is now resolved.
